on:
  push:
  workflow_dispatch:

jobs:
  saludo:
      runs-on: ubuntu-latest
      inputs:
      environment:
        description: "Un texto cualquiera"
        required: true
        type: string

      steps:
      - name: Imprimir mensaje
        run: echo "Texto: ${{ inputs.environment }}"
