on:
  workflow_dispatch:
    branches:
    - main
  inputs:
  environment:
    description: "Un texto cualquiera"
    required:  true
    type: string
  jobs:
    saludo:
      runs-on: ubuntu-latest
    steps:
      name: Imprimir mensaje
      run: echo "Texto:${{ inputs.environment }}"
